services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - /home/web/logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - webnet

  php:
    build: ./php-fpm                   # 使用自定义的 Dockerfile 来安装 mysqli 扩展
    container_name: php
    restart: always
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini  # 映射 php.ini 文件
      - ./php:/usr/local/etc/php/conf.d
      - ./html:/var/www/html
      - /home/web/logs/php:/var/log/php
    networks:
      - webnet
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

      - /home/web/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: webroot
      MYSQL_DATABASE: web
      MYSQL_USER: yinhedu
      MYSQL_PASSWORD: yinhedu147
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: yinhedu
      WORDPRESS_DB_PASSWORD: yinhedu147
      WORDPRESS_DB_NAME: web
    volumes:
      - ./html:/var/www/html
      - /home/web/logs/wp:/var/log/wp
    depends_on:
      - mysql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
